FROM node:12-alpine

RUN ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone \
  && mkdir -p /home/nodejs/app \
  && apk --no-cache --virtual build-dependencies add \
	g++ \
	gcc \
	libgcc \
	libstdc++ \
	linux-headers \
	make \
	python \
  && npm install --quiet node-gyp -g \
  && rm -rf /var/cache/apk/*
	
WORKDIR /home/nodejs/app

COPY . /home/nodejs/app

RUN mv certs/alfred_dyson_data_collector_service-key.pem certs/server.key \
	&& mv certs/alfred_dyson_data_collector_service.pem certs/server.crt 

RUN npm install nodemon \
		&& npm install

EXPOSE 3978