FROM node:11-alpine

RUN ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone \
  && mkdir -p /home/nodejs/app \
	&& apk --no-cache --virtual build-dependencies add \
	g++ \
	gcc \
	libgcc \
	libstdc++ \
	linux-headers \
	make \
	python \
  && npm install --quiet node-gyp -g \
  && rm -rf /var/cache/apk/*
	
WORKDIR /home/nodejs/app

COPY . /home/nodejs/app

RUN rm -rf node_modules \
		&& npm install nodemon \
		&& npm install

EXPOSE 3978